name: Categories
form: $/martinimultimedia/events/models/category/fields.yaml
modelClass: MartiniMultimedia\Events\Models\Category
defaultRedirect: martinimultimedia/events/categories
create:
    redirect: 'martinimultimedia/events/categories/update/:id'
    redirectClose: martinimultimedia/events/categories
update:
    redirect: martinimultimedia/events/categories
    redirectClose: martinimultimedia/events/categories
