name: Categories
form: $/moonwalkerz/events/models/category/fields.yaml
modelClass: Moonwalkerz\Events\Models\Category
defaultRedirect: moonwalkerz/events/categories
create:
    redirect: 'moonwalkerz/events/categories/update/:id'
    redirectClose: moonwalkerz/events/categories
update:
    redirect: moonwalkerz/events/categories
    redirectClose: moonwalkerz/events/categories
