list: $/moonwalkerz/events/models/tag/columns.yaml
modelClass: Moonwalkerz\Events\Models\Tag
title: Tags
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/events/tags/update/:id'
