name: Tags
form: $/martinimultimedia/events/models/tag/fields.yaml
modelClass: MartiniMultimedia\Events\Models\Tag
defaultRedirect: martinimultimedia/events/tags
create:
    redirect: 'martinimultimedia/events/tags/update/:id'
    redirectClose: martinimultimedia/events/tags
update:
    redirect: martinimultimedia/events/tags
    redirectClose: martinimultimedia/events/tags
