name: Tags
form: $/moonwalkerz/events/models/tag/fields.yaml
modelClass: MoonWalkerz\Events\Models\Tag
defaultRedirect: moonwalkerz/events/tags
create:
    redirect: 'moonwalkerz/events/tags/update/:id'
    redirectClose: moonwalkerz/events/tags
update:
    redirect: moonwalkerz/events/tags
    redirectClose: moonwalkerz/events/tags
