list: $/moonwalkerz/events/models/venue/columns.yaml
modelClass: Moonwalkerz\Events\Models\Venue
title: Venues
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/events/venues/update/:id'
