name: Venues
form: $/moonwalkerz/events/models/venue/fields.yaml
modelClass: MoonWalkerz\Events\Models\Venue
defaultRedirect: moonwalkerz/events/venues
create:
    redirect: 'moonwalkerz/events/venues/update/:id'
    redirectClose: moonwalkerz/events/venues
update:
    redirect: moonwalkerz/events/venues
    redirectClose: moonwalkerz/events/venues
