name: Events
modelClass: MoonWalkerz\Events\Models\Event
form: $/moonwalkerz/events/models/event/fields.yaml
defaultRedirect: moonwalkerz/events/events
create:
    redirect: 'moonwalkerz/events/events/update/:id'
    redirectClose: moonwalkerz/events/events
update:
    redirect: moonwalkerz/events/events
    redirectClose: moonwalkerz/events/events
